### ISSUE TITLE
[cob_collision_velocity_filter] Remaps not working

### ISSUE THREAD

**Issue by ipa-rmb** [4am-robotics/cob_control#114]
```
<remap from="command_in" to="/base/collision_velocity_filter/command" />
<remap from="command" to="/base/twist_mux/command_safe" />
```

are not working.

**Comment by fmessmer** [comment]
@ipa-rmb 
In what context/node/launchfile? What were you trying to remap?
Is this still an issue or can it be closed?

**Comment by ipa-rmb** [comment]
I do not know. Maybe you or Benni or someone else used my account to comment this while working on something? I cannot remember what this is about. If you did not write this either, maybe @ipa-bnm knows?

**Comment by floweisshardt** [comment]
then I suggest to just close this as it obviously works in the current bringup setup
