### ISSUE TITLE
cob_trajectory_controller will not stop the arm if follow_joint_traj_action is in preemption state

### ISSUE THREAD

**Issue by benmaidel** [4am-robotics/cob_control#14]
If an active follow_joint_trajectory action is aborted, the cob_trajectory_controller will never stop the control chain. Indeed he is sending the last set velocity to the driver in a loop.

This error happens if, for example, the moveit trajectory execution monitor stops a trajectory.

**Comment by floweisshardt** [comment]
this will probably not be fixed because we're switching to ros_control in indigo.

**Comment by floweisshardt** [comment]
sorry, just saw that you already provided a fix in https://github.com/ipa320/cob_control/pull/15.

**Comment by floweisshardt** [comment]
fixed with #15
