### ISSUE TITLE
missing dependency: joint_limits_interface

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_control#17]
on a fresh installation ros-indigo-joint-limits-interface is missing. This dependency is not installed using "rosdep install --from-path -i -y src"

**Comment by fmessmer** [comment]
Anyone still facing this problem?

**Comment by floweisshardt** [comment]
seems to be outdated and can be closed

**Comment by floweisshardt** [comment]
there seems to be still or again a problem with this: see Jenkins feedback http://jenkins.ros.org/job/devel-indigo-cob_gazebo_plugins/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/6/console

this is for cob_gazebo_plugins but maybe the same reason

**Comment by fmessmer** [comment]
the main problem was an undeclared transitive dependency in `gazebo_ros_control` package.
This has been fixed [here](https://github.com/ros-simulation/gazebo_ros_pkgs/pull/343)
