### ISSUE TITLE
Cob_trajectory_controller terminate after 'std::out_of_range'

### ISSUE THREAD

**Issue by kmlammers** [4am-robotics/cob_control#188]
Hello, I am attempting to use cob_trajectory_controller with Schunk PowerCube in ROS Indigo. Currently cob_trajectory_controller will receive a trajectory from MoveIt! and calculate spline-points, I have not gotten the controller to go past this point. 

Am I the first to run into this issue? 

The error:
`[ INFO] [1532625716.016360995]: getting JointNames from parameter server: //arm_controller

[ INFO] [1532625716.019458137]: starting controller with DOF: 7 PTPvel: 0.400000 PTPAcc: 0.200000 maxError 0.150000

[ INFO] [1532625716.029240961]: Setting controller frequency to 100.000000 HZ

[ INFO] [1532625805.241194266]: Received new goal trajectory with 25 points

[ INFO] [1532625805.255916046]: Calculated 26 zwischenPunkte

[ INFO] [1532625805.257592111]: Calculated 26 splinepoints

terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
[arm_controller/joint_trajectory_controller-1] process has died [pid 18717, exit code -6, cmd /home/ralab/Documents/ros/devel/lib/cob_trajectory_controller/cob_trajectory_controller __name:=joint_trajectory_controller __log:=/home/ralab/.ros/log/5717b96e-90f8-11e8-8fff-7085c274b189/arm_controller-joint_trajectory_controller-1.log].
log file: /home/ralab/.ros/log/5717b96e-90f8-11e8-8fff-7085c274b189/arm_controller-joint_trajectory_controller-1*.log
`

Best,

Kyle

**Comment by fmessmer** [comment]
both ROS Indigo and `cob_trajectory_controller` are no longer actively supported
please, try a more up-to-date combination, e.g ROS Kinetic/Melodic and the `ros_controllers/joint_trajectory_controller`
