### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [4am-robotics/cob_control#241]
Would you mind releasing this package also for the newest distribution ROS Noetic? :)

**Comment by fmessmer** [comment]
what package are you most interested in?
we haven't worked on a proper Noetic release for any of the `cob_X` repos - except for `cob_extern`
so there might be a couple of upstream dependencies missing

**Comment by Timple** [comment]
In one of our bots we use **cob_base_velocity_smoother**. Also we're evaluating the **cob_collision_velocity_filter** at the moment. So those two would be nice :)

**Comment by fmessmer** [comment]
I don't know when I will find the time for a proper Noetic release - and I don't want to do a partial release - when I start with it I'll do it for the whole cob-world
but the repo should already be Python3 compatible - thus you should at least be able to use the packages from source....please report back in case you find something not working in Noetic

**Comment by Timple** [comment]
That's fine! For now we can work from source. Consider this a placeholder issue then.

**Comment by fmessmer** [comment]
done: https://github.com/ros/rosdistro/pull/27065
