### ISSUE TITLE
Migration to ROS2

### ISSUE THREAD

**Issue by Daparrag** [4am-robotics/cob_control#278]
Hello, 

Hope you are doing well.

I wondering is there is any reason why you did not migrate the controller to latest version of ROS. In particular ROS2? do you see any impediment for that? are you considering to do the migration?, when? who? 

Thank you.

**Comment by fmessmer** [comment]
there are many packages in cob_control...are you interested it one in particular?

unfortunately, the support for this repo is reduced to a minimum only...but contributions are appreciated...

**Comment by fmessmer** [comment]
not planned
