### ISSUE TITLE
ROS Jade Release

### ISSUE THREAD

**Issue by jpetereit** [4am-robotics/cob_control#45]
Desperately waiting for it :)
Is there any blocking issue or anything I can help you with?

xref: ipa320/schunk_modular_robotics#142

**Comment by fmessmer** [comment]
See my [comment](https://github.com/ipa320/schunk_modular_robotics/issues/142#issuecomment-123476713). Let's focus the Jade Release discussion [there](https://github.com/ipa320/schunk_modular_robotics/issues/142)
