### ISSUE TITLE
Builfarm error for cob_obstacle_distance

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_control#48]
see http://jenkins.ros.org/job/devel-indigo-cob_control/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/30/console

**Comment by fmessmer** [comment]
should be fixed by https://github.com/ipa-fxm/cob_control/commit/ca7b536390bcf76bf4ab6e62354c52bd51fb1ece in #47
