### ISSUE TITLE
[cob_cartesian_controller] Re-work/fix cob_cartesian_controller

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_control#52]
ToDo's:
- ~~review, verify and re-structure profile_generator library (unification of sinoid/ramp for linear/circular, use design pattern)~~ #74 
- ~~better Action interface for cob_cartesian_controller (e.g. separate MoveLin and MoveCirc actions?)~~ #75
- ~~more Cartesian trajectories (e.g. 3-point MoveCirc)~~ #69 
- ~~more Cartesian trajectories (e.g. list of waypoints)~~ #69 
- ~~trajectory blending~~ #69 
- ~~finalize/unify Python interface (`simple_cartesian_interface`)~~ #75
- How can we guarantee that the end-effector is at the correct starting pose for a given Cartesian motion?
- ~~use Action interface of `cob_frame_tracker` rather than Service interface~~ #75
- ~~rework/improve safety-/abortion-/hold_twist criteria (remove from `cob_cartesian_controller`, improve in `cob_frame_tracker`)~~ #75
- limit twists (either outgoing provided `cob_frame_tracker` or incoming into `cob_twist_controller`
- ~~finally `roslint` the package (http://wiki.ros.org/roslint)~~ #74 

together with @ipa-fxm-cm

**Comment by MaChristoph** [comment]
-Restructured profile_generator with factory builder approach
-Matrix sort not longer necessary
-Implemented a method to achieve equal array sizes (Adjust array length function only used in a special case. (Check out the code comment) )
-Combined several functionalities and simplified the code structure
-Might fixed the "Square box is not really a Box" problem ( Can be checked after the ToDo from below is fixed)

ToDo:
-There's still a bug in the optimized trajectory interpolation ( Path too short for a given velocity and acceleration )

**Comment by fmessmer** [comment]
I extracted everything related to additional/new Cartesian motion primitives to a new issue https://github.com/ipa320/cob_control/issues/69.

**Comment by fmessmer** [comment]
Current progress is reviewed in https://github.com/ipa-fxm/cob_control/pull/9

**Comment by fmessmer** [comment]
I extracted everything related to re-working the action interfaces and abortion criteria to a new issue #75.

**Comment by fmessmer** [comment]
Fixed in #74 (after the latest changes from my `test_new_cartesian_controller` branch have been merged!)

All the other open bullets are minor, mostly done, not relevant anymore or to be marked as wontfix.

**Comment by MaChristoph** [comment]
How can we guarantee that the end-effector is at the correct starting pose for a given Cartesian motion?
- move_lin: It is using the current starting position of the EE, therefore it is always in its starting position for the linear motion.
- move_circ: Maybe we can use a linear motion from the current pose to the starting pose of move_circ motion. Another possibility is to use move it! to reach the starting position with a "PTP" motion.

**Comment by fmessmer** [comment]
Most is done in #74, few has been separated into #69 and #75, rest is `WONTFIX` or `FIXONUSAGE`...
:point_right: closing!
