### ISSUE TITLE
not building on first try due to missing cob_srvs_gencpp in cob_trajectory_controller

### ISSUE THREAD

**Issue by mgruhler** [4am-robotics/cob_control#6]

**Comment by floweisshardt** [comment]
@ipa-fxm can you please look into that?

**Comment by mgruhler** [comment]
@ipa-fmw: Just discussed it with @ipa-fxm. How is the official policy for this?
The cob_srvs dependency is in there (in package.xml as build and run dep, in CmakeLists.txt catkin_package and is find_packaged). But do you need to add an add_dependencies(TARGET MSG_PKG_gencpp) for each msg that you take from other packages?

---

Dipl.-Ing. Matthias GRUHLER
Wissenschaftlicher Mitarbeiter
Research Assistant

Fraunhofer-Institut für Produktionstechnik und Automatisierung IPA

Servicerobotik für Industrie und Gewerbe
Industrial Service Robotics

Abteilung Roboter- und Assistenzsysteme
Department Robot and Assistive Systems

Nobelstraße 12 │ 70569 Stuttgart
Phone +49 711 970-1315
Fax +49 711 970-1008

Matthias.Gruhler@ipa.fraunhofer.demailto:Matthias.Gruhler@ipa.fraunhofer.de
www.ipa.fraunhofer.dehttp://www.ipa.fraunhofer.de/
www.care-o-bot.dehttp://www.care-o-bot.de/

Von: Florian Weisshardt [mailto:notifications@github.com]
Gesendet: Dienstag, 22. Juli 2014 15:48
An: ipa320/cob_control
Cc: Gruhler, Matthias
Betreff: Re: [cob_control] not building on first try due to missing cob_srvs_gencpp in cob_trajectory_controller (#6)

@ipa-fxmhttps://github.com/ipa-fxm can you please look into that?

**Comment by floweisshardt** [comment]
the solution by @ipa-fxm is that you have to add it: 
e.g. add_dependencies(${PROJECT_NAME} cob_msgs_gencpp)
